server:
  port: 80


#Eureka配置
eureka:
  client:
    register-with-eureka: false #不想Eureka注册自己
    service-url:
#      单机 http://localhost:7003/eureka/
#      集群 http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://localhost:7003/eureka/

#开启降级 feign.hystrix
feign:
  hystrix:
    enabled: true
